In [1]:
M = 'bomba'
S = 'senha'

In [8]:
def criptografa(M: str, S: str)-> str:
    res = ''
    for letra, letra_senha in zip(M, S):
        print(letra, letra_senha)

    return res


In [3]:
criptografa(M, S)

b s
o e
m n
b h
a a


''

In [85]:
def letra_to_int(letra : str) -> int:
    return ord(letra)

In [86]:
letra_to_int('m')

109

In [11]:
def int_to_letra(i: int) -> str:
    return chr(i)

In [12]:
int_to_letra(109)

'm'

## testando int to bin

In [14]:
int_to_bin(108)

'0b1101100'

In [26]:
binario_com_prefixo = '0b1100' #'0b1101100'

In [27]:
binario_sem_prefixo = binario_com_prefixo[2:]

In [28]:
binario_size_8 = binario_sem_prefixo

In [29]:
while(len(binario_size_8)<8):
    binario_size_8 = '0' + binario_size_8

In [30]:
binario_size_8

'00001100'

In [31]:
list(binario_size_8)

['0', '0', '0', '0', '1', '1', '0', '0']

In [53]:
from typing import List
def int_to_bin(i: int) -> List[int]:
    
    binario_com_prefixo = bin(i)
    binario_sem_prefixo = binario_com_prefixo[2:]
    binario_size_8 = binario_sem_prefixo
    
    while(len(binario_size_8)<8):
        binario_size_8 = '0' + binario_size_8
    
    return [int(i) for i in list(binario_size_8)]

In [54]:
int_to_bin(108)

[0, 1, 1, 0, 1, 1, 0, 0]

## testando bin to int

In [55]:
binario = [0, 1, 1, 0, 1, 1, 0, 0]

In [42]:
for b in reversed(binario):
    print(b)

0
0
1
1
0
1
1
0


In [43]:
for i, b in enumerate(reversed(binario)):
    print(i, b)

0 0
1 0
2 1
3 1
4 0
5 1
6 1
7 0


In [56]:
numero = 0
for i, b in enumerate(reversed(binario)):
    numero += int(b)*(2**i)
    print(i, b, 2**i, b*(2**i))
print(numero)

0 0 1 0
1 0 2 0
2 1 4 4
3 1 8 8
4 0 16 0
5 1 32 32
6 1 64 64
7 0 128 0
108


In [57]:
from typing import List
def bin_to_int(binario: List[int]) -> int:
    numero = 0
    for i, b in enumerate(reversed(binario)):
        numero += int(b)*(2**i)
    return numero

In [58]:
bin_to_int([0, 1, 1, 0, 1, 1, 0, 0])

108

## testando XOR

In [65]:
bin1 = [0, 1, 1, 0, 1, 1, 0, 0]
bin2 = [0, 1, 1, 0, 0, 1, 0, 1]

In [66]:
import numpy as np

In [67]:
np.array(bin1)

array([0, 1, 1, 0, 1, 1, 0, 0])

In [69]:
res = np.logical_xor(bin1, bin2)

In [70]:
res

array([False, False, False, False,  True, False, False,  True])

In [71]:
type(res)

numpy.ndarray

In [72]:
res.astype(int)

array([0, 0, 0, 0, 1, 0, 0, 1])

In [73]:
list(res.astype(int))

[0, 0, 0, 0, 1, 0, 0, 1]

In [74]:
type(list(res.astype(int)))

list

In [94]:
def xor_de_byte(byte1: List[int], byte2: List[int]) -> List[int]:
    res = np.logical_xor(byte1, byte2)
    res = res.astype(int)
    res = list(res)
    return res

In [95]:
xor_de_byte([0, 1, 1, 0, 1, 1, 0, 0], [0, 1, 1, 0, 0, 1, 0, 0])

[0, 0, 0, 0, 1, 0, 0, 0]

In [103]:
def criptografa_letra(letra1: str, letra2: str)-> str:
    int1 = letra_to_int(letra1)
    bin1 = int_to_bin(int1)
    int2 = letra_to_int(letra2)
    bin2 = int_to_bin(int2)
    
    res_byte = xor_de_byte(bin1, bin2)
    
    res_int = bin_to_int(res_byte)

    res = int_to_letra(res_int)
    print(res)
    return res


In [106]:
criptografa_letra('m', '\x1d')

[0, 1, 1, 1, 0, 0, 0, 0]
p


'p'

In [107]:
criptografa_letra('m', 'm')

[0, 0, 0, 0, 0, 0, 0, 0]



'\x00'

In [108]:
criptografa_letra('m', '\x00')

[0, 1, 1, 0, 1, 1, 0, 1]
m


'm'

In [109]:
def criptografa(M: str, S: str)-> str:
    res = ''
    for letra, letra_senha in zip(M, S):
        res += criptografa_letra(letra, letra_senha)

    return res


In [110]:
criptografa(M, S)

[0, 0, 0, 1, 0, 0, 0, 1]

[0, 0, 0, 0, 1, 0, 1, 0]


[0, 0, 0, 0, 0, 0, 1, 1]

[0, 0, 0, 0, 1, 0, 1, 0]


[0, 0, 0, 0, 0, 0, 0, 0]



'\x11\n\x03\n\x00'

In [111]:
criptografa('\x11\n\x03\n\x00', S)

[0, 1, 1, 0, 0, 0, 1, 0]
b
[0, 1, 1, 0, 1, 1, 1, 1]
o
[0, 1, 1, 0, 1, 1, 0, 1]
m
[0, 1, 1, 0, 0, 0, 1, 0]
b
[0, 1, 1, 0, 0, 0, 0, 1]
a


'bomba'